version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: audiofilter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  python-backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python_backend:/app
    depends_on:
      - minio

volumes:
  postgres_data:
  minio_data:
